### ISSUE TITLE
parse_frontmatter: ValueError: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by ysr23** [gwgundersen/anno#13]
getting this error on first run:
`parse_frontmatter: ValueError: not enough values to unpack (expected 3, got 1)`

Python 3.7.1
Flask 1.1.1

in a folder with one `.anno.md` file: `2020-01-06.anno.md` - attempted with:
```
mkdir foo
touch bar.anno.md
anno
```
same problem

```
 * Serving Flask app "anno.anno.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [14/Jan/2020 10:22:10] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/anno/anno/app.py", line 37, in index
    notes = get_notes()
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/anno/anno/notes.py", line 27, in get_notes
    note = Note.from_fname(f)
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/anno/anno/notes.py", line 154, in from_fname
    return cls(text, orig_fname=fname)
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/anno/anno/notes.py", line 120, in __init__
    fm = parse_frontmatter(text)
  File "/Users/ysr23/anaconda3/lib/python3.7/site-packages/anno/anno/render.py", line 36, in parse_frontmatter
    _, fm, content = FM_BOUNDARY.split(text, 2)
```

**Comment by gwgundersen** [comment]
Currently, Anno is opinionated that files should be in the format `YYYY-MM-DD-filename.anno.md`*. The simplest way to create a new file is via Anno's UI. So launch the program and click "Create note". Please re-open if this isn't the issue.

_*This was probably a design mistake on my part, and I may remove the restriction._
